language: python

python:
  - 3.7

stage: test
install:
  - pip install awscli
  - mkdir -p results || true
  - git config --global user.email "${GH_EMAIL}"
  - git config --global user.name "YakDriver"
script:
  - source get_instance_types.sh
  - write_instance_info
  - git checkout main
  - git add ./results/*
  - git add README.md
  - git add offering_header.md
  - git commit -m "Update EC2 instance types with build $TRAVIS_BUILD_NUMBER"
  - git remote add commit-origin https://${GH_TOKEN}@github.com/YakDriver/aws-ec2-instance-types.git > /dev/null 2>&1
  - git push --quiet --set-upstream commit-origin main 
